server:
  port: 8072
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: config_server
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT `key`, `value` from properties where application=? and profile=? and label=?
  datasource:
    #name: test
    url: jdbc:mysql://101.201.235.239:3306/wt_config
#    username: root
    username: develop
    #使用远程的配置中心的参数
#    password: W5dAJxRr)A]p
    password: bit2019!Q2w3e

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  config-location:  classpath:mybatis-config.xml

logging:
  level:
     com.bit.soft.configserver.dao : debug

#设置登录用户
login:
  name: DBA
  password: 888888