eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
server:
  port: 8088
spring:
  zipkin:
    base-url: http://localhost:8085
  sleuth:
    sampler:
      percentage: 1.0
  jackson:
    serialization:
      write-dates-as-timestamps: true
  rabbitmq:
    host: 101.201.235.239
    port: 5672
    username: guest
    password: guest
  application:
    name: service-cbo
  datasource:
    #name: test
    url: jdbc:mysql://101.201.235.239:3306/wt_cbo?characterEncoding=utf-8
    username: develop
    #使用远程的配置中心的参数
    password: bit2019!Q2w3e
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  data:
    mongodb:
      uri: mongodb://tester:1qaz2wsx@101.201.235.239:27017/test
hystrix:
  threadpool:
    default:
      coreSize: 500  #并发执行的最大线程数，默认10
  command:
    paas-file:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 36000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000  #命令执行超时时间，默认1000ms
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream
redis:
  hostName: 101.201.235.239
  port: 6379
  timeout: 30
  maxIdle : 300
  maxTotal: 1000
  maxWaitMillis: 1000
  minEvictableIdleTimeMillis : 300000
  numTestsPerEvictionRun : 1024
  timeBetweenEvictionRunsMillis : 30000
  testOnBorrow : true
  testWhileIdle : true
  password: bit2019
mybatis:
  mapper-locations: classpath:mybatis-mapper/*.xml
  config-location:  classpath:mybatis-config.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: countSql
logging:
  level:
    com.bit.module.cbo.dao : debug
#atToken过期时间
atToken:
  expire: 86400
#rtToken过期时间
rtToken:
  expire: 604800

feign:
  hystrix:
    enabled: true
extend-type:
  type:
    1: basicLivingAllowancesImpl
    2: residentApplyHomeCareImpl